# All proposals must follow the template, so disallow creating blank issues.
blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://github.com/redot-engine/redot-proposals/discussions
    about: Discuss any idea related to improving Redot

  - name: Main Redot repository
    url: https://github.com/redot-engine/redot-engine
    about: Report bugs on the main Godot repository
